// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.policybazar.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class MemberInfo_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_fullName_QNAME = new QName("", "fullName");
    private static final javax.xml.namespace.QName ns3_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns3_myns3_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns1_age_QNAME = new QName("", "age");
    private static final javax.xml.namespace.QName ns3_int_TYPE_QNAME = SchemaConstants.QNAME_TYPE_INT;
    private CombinedSerializer ns3_myns3__int__int_Int_Serializer;
    private static final javax.xml.namespace.QName ns1_gender_QNAME = new QName("", "gender");
    private static final javax.xml.namespace.QName ns1_contact$2d$no_QNAME = new QName("", "contact-no");
    private static final javax.xml.namespace.QName ns1_email$2d$address_QNAME = new QName("", "email-address");
    private static final int myFULLNAME_INDEX = 0;
    private static final int myAGE_INDEX = 1;
    private static final int myGENDER_INDEX = 2;
    private static final int myCONTACTNO_INDEX = 3;
    private static final int myEMAILADDRESS_INDEX = 4;
    
    public MemberInfo_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns3_myns3_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String.class, ns3_string_TYPE_QNAME);
        ns3_myns3__int__int_Int_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, int.class, ns3_int_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.policybazar.service.MemberInfo instance = new com.policybazar.service.MemberInfo();
        com.policybazar.service.MemberInfo_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_fullName_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_fullName_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.policybazar.service.MemberInfo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myFULLNAME_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setFullName((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_age_QNAME)) {
                member = ns3_myns3__int__int_Int_Serializer.deserialize(ns1_age_QNAME, reader, context);
                instance.setAge(((java.lang.Integer)member).intValue());
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_gender_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_gender_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.policybazar.service.MemberInfo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myGENDER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setGender((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_contact$2d$no_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_contact$2d$no_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.policybazar.service.MemberInfo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCONTACTNO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setContactNo((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_email$2d$address_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_email$2d$address_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.policybazar.service.MemberInfo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myEMAILADDRESS_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setEmailAddress((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.policybazar.service.MemberInfo instance = (com.policybazar.service.MemberInfo)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.policybazar.service.MemberInfo instance = (com.policybazar.service.MemberInfo)obj;
        
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getFullName(), ns1_fullName_QNAME, null, writer, context);
        ns3_myns3__int__int_Int_Serializer.serialize(new java.lang.Integer(instance.getAge()), ns1_age_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getGender(), ns1_gender_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getContactNo(), ns1_contact$2d$no_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getEmailAddress(), ns1_email$2d$address_QNAME, null, writer, context);
    }
}
