// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.policybazar.service;


public class MemberInfo {
    protected java.lang.String fullName;
    protected int age;
    protected java.lang.String gender;
    protected java.lang.String contactNo;
    protected java.lang.String emailAddress;
    
    public MemberInfo() {
    }
    
    public MemberInfo(java.lang.String fullName, int age, java.lang.String gender, java.lang.String contactNo, java.lang.String emailAddress) {
        this.fullName = fullName;
        this.age = age;
        this.gender = gender;
        this.contactNo = contactNo;
        this.emailAddress = emailAddress;
    }
    
    public java.lang.String getFullName() {
        return fullName;
    }
    
    public void setFullName(java.lang.String fullName) {
        this.fullName = fullName;
    }
    
    public int getAge() {
        return age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    
    public java.lang.String getGender() {
        return gender;
    }
    
    public void setGender(java.lang.String gender) {
        this.gender = gender;
    }
    
    public java.lang.String getContactNo() {
        return contactNo;
    }
    
    public void setContactNo(java.lang.String contactNo) {
        this.contactNo = contactNo;
    }
    
    public java.lang.String getEmailAddress() {
        return emailAddress;
    }
    
    public void setEmailAddress(java.lang.String emailAddress) {
        this.emailAddress = emailAddress;
    }
}
