// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.policybazar.service;

public interface PolicyManager extends java.rmi.Remote {
    public com.policybazar.service.Policy enroll(com.policybazar.service.MemberInfo memberInfo, com.policybazar.service.EnrollmentInfo enrollmentInfo) throws 
         java.rmi.RemoteException;
}
