// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.policybazar.service;


public class PolicyManager_enroll_RequestStruct {
    protected com.policybazar.service.MemberInfo memberInfo;
    protected com.policybazar.service.EnrollmentInfo enrollmentInfo;
    
    public PolicyManager_enroll_RequestStruct() {
    }
    
    public PolicyManager_enroll_RequestStruct(com.policybazar.service.MemberInfo memberInfo, com.policybazar.service.EnrollmentInfo enrollmentInfo) {
        this.memberInfo = memberInfo;
        this.enrollmentInfo = enrollmentInfo;
    }
    
    public com.policybazar.service.MemberInfo getMemberInfo() {
        return memberInfo;
    }
    
    public void setMemberInfo(com.policybazar.service.MemberInfo memberInfo) {
        this.memberInfo = memberInfo;
    }
    
    public com.policybazar.service.EnrollmentInfo getEnrollmentInfo() {
        return enrollmentInfo;
    }
    
    public void setEnrollmentInfo(com.policybazar.service.EnrollmentInfo enrollmentInfo) {
        this.enrollmentInfo = enrollmentInfo;
    }
}
