// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.policybazar.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class Policy_SOAPBuilder implements SOAPInstanceBuilder {
    private com.policybazar.service.Policy _instance;
    private java.lang.String policyNo;
    private java.lang.String policyHolderName;
    private java.util.Calendar effectiveFrom;
    private java.util.Calendar validTill;
    private float insurredAmount;
    private static final int myPOLICYNO_INDEX = 0;
    private static final int myPOLICYHOLDERNAME_INDEX = 1;
    private static final int myEFFECTIVEFROM_INDEX = 2;
    private static final int myVALIDTILL_INDEX = 3;
    private static final int myINSURREDAMOUNT_INDEX = 4;
    
    public Policy_SOAPBuilder() {
    }
    
    public void setPolicyNo(java.lang.String policyNo) {
        this.policyNo = policyNo;
    }
    
    public void setPolicyHolderName(java.lang.String policyHolderName) {
        this.policyHolderName = policyHolderName;
    }
    
    public void setEffectiveFrom(java.util.Calendar effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }
    
    public void setValidTill(java.util.Calendar validTill) {
        this.validTill = validTill;
    }
    
    public void setInsurredAmount(float insurredAmount) {
        this.insurredAmount = insurredAmount;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myPOLICYNO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPOLICYHOLDERNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myPOLICYNO_INDEX:
                    _instance.setPolicyNo((java.lang.String)memberValue);
                    break;
                case myPOLICYHOLDERNAME_INDEX:
                    _instance.setPolicyHolderName((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.policybazar.service.Policy)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
