// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.policybazar.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class PolicyManager_enroll_RequestStruct_SOAPBuilder implements SOAPInstanceBuilder {
    private com.policybazar.service.PolicyManager_enroll_RequestStruct _instance;
    private com.policybazar.service.MemberInfo memberInfo;
    private com.policybazar.service.EnrollmentInfo enrollmentInfo;
    private static final int myMEMBERINFO_INDEX = 0;
    private static final int myENROLLMENTINFO_INDEX = 1;
    
    public PolicyManager_enroll_RequestStruct_SOAPBuilder() {
    }
    
    public void setMemberInfo(com.policybazar.service.MemberInfo memberInfo) {
        this.memberInfo = memberInfo;
    }
    
    public void setEnrollmentInfo(com.policybazar.service.EnrollmentInfo enrollmentInfo) {
        this.enrollmentInfo = enrollmentInfo;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myMEMBERINFO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myENROLLMENTINFO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myMEMBERINFO_INDEX:
                    _instance.setMemberInfo((com.policybazar.service.MemberInfo)memberValue);
                    break;
                case myENROLLMENTINFO_INDEX:
                    _instance.setEnrollmentInfo((com.policybazar.service.EnrollmentInfo)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.policybazar.service.PolicyManager_enroll_RequestStruct)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
