// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.policybazar.service;


public class Policy {
    protected java.lang.String policyNo;
    protected java.lang.String policyHolderName;
    protected java.util.Calendar effectiveFrom;
    protected java.util.Calendar validTill;
    protected float insurredAmount;
    
    public Policy() {
    }
    
    public Policy(java.lang.String policyNo, java.lang.String policyHolderName, java.util.Calendar effectiveFrom, java.util.Calendar validTill, float insurredAmount) {
        this.policyNo = policyNo;
        this.policyHolderName = policyHolderName;
        this.effectiveFrom = effectiveFrom;
        this.validTill = validTill;
        this.insurredAmount = insurredAmount;
    }
    
    public java.lang.String getPolicyNo() {
        return policyNo;
    }
    
    public void setPolicyNo(java.lang.String policyNo) {
        this.policyNo = policyNo;
    }
    
    public java.lang.String getPolicyHolderName() {
        return policyHolderName;
    }
    
    public void setPolicyHolderName(java.lang.String policyHolderName) {
        this.policyHolderName = policyHolderName;
    }
    
    public java.util.Calendar getEffectiveFrom() {
        return effectiveFrom;
    }
    
    public void setEffectiveFrom(java.util.Calendar effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }
    
    public java.util.Calendar getValidTill() {
        return validTill;
    }
    
    public void setValidTill(java.util.Calendar validTill) {
        this.validTill = validTill;
    }
    
    public float getInsurredAmount() {
        return insurredAmount;
    }
    
    public void setInsurredAmount(float insurredAmount) {
        this.insurredAmount = insurredAmount;
    }
}
