// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.religareinsurance.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class MemberInfo_SOAPBuilder implements SOAPInstanceBuilder {
    private com.religareinsurance.service.MemberInfo _instance;
    private java.lang.String fullName;
    private int age;
    private java.lang.String gender;
    private java.lang.String contactNo;
    private java.lang.String emailAddress;
    private static final int myFULLNAME_INDEX = 0;
    private static final int myAGE_INDEX = 1;
    private static final int myGENDER_INDEX = 2;
    private static final int myCONTACTNO_INDEX = 3;
    private static final int myEMAILADDRESS_INDEX = 4;
    
    public MemberInfo_SOAPBuilder() {
    }
    
    public void setFullName(java.lang.String fullName) {
        this.fullName = fullName;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    
    public void setGender(java.lang.String gender) {
        this.gender = gender;
    }
    
    public void setContactNo(java.lang.String contactNo) {
        this.contactNo = contactNo;
    }
    
    public void setEmailAddress(java.lang.String emailAddress) {
        this.emailAddress = emailAddress;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myFULLNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myGENDER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCONTACTNO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEMAILADDRESS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myFULLNAME_INDEX:
                    _instance.setFullName((java.lang.String)memberValue);
                    break;
                case myGENDER_INDEX:
                    _instance.setGender((java.lang.String)memberValue);
                    break;
                case myCONTACTNO_INDEX:
                    _instance.setContactNo((java.lang.String)memberValue);
                    break;
                case myEMAILADDRESS_INDEX:
                    _instance.setEmailAddress((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.religareinsurance.service.MemberInfo)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
