// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.religareinsurance.service;

public interface PolicyManager extends java.rmi.Remote {
    public com.religareinsurance.service.Policy enroll(com.religareinsurance.service.MemberInfo memberInfo, com.religareinsurance.service.EnrollmentInfo enrollmentInfo) throws 
         java.rmi.RemoteException;
}
