// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.religareinsurance.service;


public class PolicyManager_enroll_ResponseStruct {
    protected com.religareinsurance.service.Policy result;
    
    public PolicyManager_enroll_ResponseStruct() {
    }
    
    public PolicyManager_enroll_ResponseStruct(com.religareinsurance.service.Policy result) {
        this.result = result;
    }
    
    public com.religareinsurance.service.Policy getResult() {
        return result;
    }
    
    public void setResult(com.religareinsurance.service.Policy result) {
        this.result = result;
    }
}
