// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.religareinsurance.service;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class PolicyManager_enroll_RequestStruct_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_memberInfo_QNAME = new QName("", "memberInfo");
    private static final javax.xml.namespace.QName ns2_memberInfo_TYPE_QNAME = new QName("http://www.religare.com/insurance/types", "memberInfo");
    private CombinedSerializer ns2_myMemberInfo_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_enrollmentInfo_QNAME = new QName("", "enrollmentInfo");
    private static final javax.xml.namespace.QName ns2_enrollmentInfo_TYPE_QNAME = new QName("http://www.religare.com/insurance/types", "enrollmentInfo");
    private CombinedSerializer ns2_myEnrollmentInfo_SOAPSerializer;
    private static final int myMEMBERINFO_INDEX = 0;
    private static final int myENROLLMENTINFO_INDEX = 1;
    
    public PolicyManager_enroll_RequestStruct_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns2_myMemberInfo_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.religareinsurance.service.MemberInfo.class, ns2_memberInfo_TYPE_QNAME);
        ns2_myEnrollmentInfo_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.religareinsurance.service.EnrollmentInfo.class, ns2_enrollmentInfo_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.religareinsurance.service.PolicyManager_enroll_RequestStruct instance = new com.religareinsurance.service.PolicyManager_enroll_RequestStruct();
        com.religareinsurance.service.PolicyManager_enroll_RequestStruct_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        for (int i=0; i<2; i++) {
            elementName = reader.getName();
            if (reader.getState() == XMLReader.END) {
                break;
            }
            if (elementName.equals(ns1_memberInfo_QNAME)) {
                member = ns2_myMemberInfo_SOAPSerializer.deserialize(ns1_memberInfo_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.religareinsurance.service.PolicyManager_enroll_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myMEMBERINFO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setMemberInfo((com.religareinsurance.service.MemberInfo)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_enrollmentInfo_QNAME)) {
                member = ns2_myEnrollmentInfo_SOAPSerializer.deserialize(ns1_enrollmentInfo_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.religareinsurance.service.PolicyManager_enroll_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myENROLLMENTINFO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setEnrollmentInfo((com.religareinsurance.service.EnrollmentInfo)member);
                }
                reader.nextElementContent();
                continue;
            } else {
                throw new DeserializationException("soap.unexpectedElementName", new Object[] {ns1_enrollmentInfo_QNAME, elementName});
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.religareinsurance.service.PolicyManager_enroll_RequestStruct instance = (com.religareinsurance.service.PolicyManager_enroll_RequestStruct)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.religareinsurance.service.PolicyManager_enroll_RequestStruct instance = (com.religareinsurance.service.PolicyManager_enroll_RequestStruct)obj;
        
        ns2_myMemberInfo_SOAPSerializer.serialize(instance.getMemberInfo(), ns1_memberInfo_QNAME, null, writer, context);
        ns2_myEnrollmentInfo_SOAPSerializer.serialize(instance.getEnrollmentInfo(), ns1_enrollmentInfo_QNAME, null, writer, context);
    }
}
