package com.goair.travel.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-08-03T23:07:18.590-04:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://www.goair.com/travel/service", name = "TicketManager")
@XmlSeeAlso({com.goair.travel.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TicketManager {

    @WebMethod(action = "http://www.goair.com/travel/service/bookTicket")
    @WebResult(name = "airTicket", targetNamespace = "http://www.goair.com/travel/types", partName = "ticket")
    public com.goair.travel.types.AirTicket bookTicket(

        @WebParam(partName = "travelPlan", name = "travelPlan", targetNamespace = "http://www.goair.com/travel/types")
        com.goair.travel.types.TravelPlan travelPlan
    );
}
