package com.goair.travel.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-08-03T23:07:18.603-04:00
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "TicketManagerService",
                  wsdlLocation = "http://localhost:8081/goair/services/ticketManager?wsdl",
                  targetNamespace = "http://www.goair.com/travel/service")
public class TicketManagerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.goair.com/travel/service", "TicketManagerService");
    public final static QName TicketManagerSOAPPort = new QName("http://www.goair.com/travel/service", "TicketManagerSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/goair/services/ticketManager?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TicketManagerService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/goair/services/ticketManager?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TicketManagerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TicketManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketManagerService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TicketManagerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TicketManagerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TicketManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TicketManager
     */
    @WebEndpoint(name = "TicketManagerSOAPPort")
    public TicketManager getTicketManagerSOAPPort() {
        return super.getPort(TicketManagerSOAPPort, TicketManager.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketManager
     */
    @WebEndpoint(name = "TicketManagerSOAPPort")
    public TicketManager getTicketManagerSOAPPort(WebServiceFeature... features) {
        return super.getPort(TicketManagerSOAPPort, TicketManager.class, features);
    }

}
