//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.27 at 09:07:21 PM EDT 
//

package org.lic.insurance.policy;

import java.util.Date;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for memberInfoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="memberInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fullname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dob" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="aadhar-no" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "memberInfoType", propOrder = { "fullname", "dob", "gender", "aadharNo" })
public class MemberInfoType {

	@XmlElement(required = true)
	protected String fullname;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected Date dob;
	@XmlElement(required = true)
	protected String gender;
	@XmlElement(name = "aadhar-no", required = true)
	protected String aadharNo;

	/**
	 * Gets the value of the fullname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * Sets the value of the fullname property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setFullname(String value) {
		this.fullname = value;
	}

	public Date getDob() {
		return dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	/**
	 * Gets the value of the gender property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * Sets the value of the gender property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setGender(String value) {
		this.gender = value;
	}

	/**
	 * Gets the value of the aadharNo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAadharNo() {
		return aadharNo;
	}

	/**
	 * Sets the value of the aadharNo property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAadharNo(String value) {
		this.aadharNo = value;
	}

}
