
package com.upstock.trading.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;

/**
 * This class was generated by the XML-WS Tools. XML-WS Tools 4.0.0 Generated
 * source version: 3.0
 * 
 */
@WebServiceClient(name = "StockManagerImplService", targetNamespace = "http://service.trading.upstock.com/", wsdlLocation = "http://localhost:8081/upstock/stockmanager?wsdl")
public class StockManagerImplService extends Service {

	private final static URL STOCKMANAGERIMPLSERVICE_WSDL_LOCATION;
	private final static WebServiceException STOCKMANAGERIMPLSERVICE_EXCEPTION;
	private final static QName STOCKMANAGERIMPLSERVICE_QNAME = new QName("http://service.trading.upstock.com/",
			"StockManagerImplService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL("http://localhost:8081/upstock/stockmanager?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		STOCKMANAGERIMPLSERVICE_WSDL_LOCATION = url;
		STOCKMANAGERIMPLSERVICE_EXCEPTION = e;
	}

	public StockManagerImplService() {
		super(__getWsdlLocation(), STOCKMANAGERIMPLSERVICE_QNAME);
	}

	public StockManagerImplService(WebServiceFeature... features) {
		super(__getWsdlLocation(), STOCKMANAGERIMPLSERVICE_QNAME, features);
	}

	public StockManagerImplService(URL wsdlLocation) {
		super(wsdlLocation, STOCKMANAGERIMPLSERVICE_QNAME);
	}

	public StockManagerImplService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, STOCKMANAGERIMPLSERVICE_QNAME, features);
	}

	public StockManagerImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public StockManagerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns StockManager
	 */
	@WebEndpoint(name = "StockManagerImplPort")
	public StockManager getStockManagerImplPort() {
		return super.getPort(new QName("http://service.trading.upstock.com/", "StockManagerImplPort"),
				StockManager.class);
	}

	/**
	 * 
	 * @param features A list of {@link jakarta.xml.ws.WebServiceFeature} to
	 *                 configure on the proxy. Supported features not in the
	 *                 <code>features</code> parameter will have their default
	 *                 values.
	 * @return returns StockManager
	 */
	@WebEndpoint(name = "StockManagerImplPort")
	public StockManager getStockManagerImplPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://service.trading.upstock.com/", "StockManagerImplPort"),
				StockManager.class, features);
	}

	private static URL __getWsdlLocation() {
		if (STOCKMANAGERIMPLSERVICE_EXCEPTION != null) {
			throw STOCKMANAGERIMPLSERVICE_EXCEPTION;
		}
		return STOCKMANAGERIMPLSERVICE_WSDL_LOCATION;
	}

}
