//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.27 at 09:07:21 PM EDT 
//


package org.lic.insurance.policy;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for planType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="planType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="plan-no" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="plan-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="plan-type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="min-eligibility-age" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="max-eligibility-age" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="min-insurred-amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "planType", propOrder = {
    "planNo",
    "planName",
    "planType",
    "minEligibilityAge",
    "maxEligibilityAge",
    "minInsurredAmount"
})
public class PlanType {

    @XmlElement(name = "plan-no", required = true)
    protected String planNo;
    @XmlElement(name = "plan-name", required = true)
    protected String planName;
    @XmlElement(name = "plan-type", required = true)
    protected String planType;
    @XmlElement(name = "min-eligibility-age")
    protected int minEligibilityAge;
    @XmlElement(name = "max-eligibility-age")
    protected int maxEligibilityAge;
    @XmlElement(name = "min-insurred-amount")
    protected float minInsurredAmount;

    /**
     * Gets the value of the planNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanNo() {
        return planNo;
    }

    /**
     * Sets the value of the planNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanNo(String value) {
        this.planNo = value;
    }

    /**
     * Gets the value of the planName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * Sets the value of the planName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanName(String value) {
        this.planName = value;
    }

    /**
     * Gets the value of the planType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanType() {
        return planType;
    }

    /**
     * Sets the value of the planType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanType(String value) {
        this.planType = value;
    }

    /**
     * Gets the value of the minEligibilityAge property.
     * 
     */
    public int getMinEligibilityAge() {
        return minEligibilityAge;
    }

    /**
     * Sets the value of the minEligibilityAge property.
     * 
     */
    public void setMinEligibilityAge(int value) {
        this.minEligibilityAge = value;
    }

    /**
     * Gets the value of the maxEligibilityAge property.
     * 
     */
    public int getMaxEligibilityAge() {
        return maxEligibilityAge;
    }

    /**
     * Sets the value of the maxEligibilityAge property.
     * 
     */
    public void setMaxEligibilityAge(int value) {
        this.maxEligibilityAge = value;
    }

    /**
     * Gets the value of the minInsurredAmount property.
     * 
     */
    public float getMinInsurredAmount() {
        return minInsurredAmount;
    }

    /**
     * Sets the value of the minInsurredAmount property.
     * 
     */
    public void setMinInsurredAmount(float value) {
        this.minInsurredAmount = value;
    }

}
