// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.railyatra.services;


public class TrainEnquiry_pnrStatus_ResponseStruct {
    protected java.lang.String result;
    
    public TrainEnquiry_pnrStatus_ResponseStruct() {
    }
    
    public TrainEnquiry_pnrStatus_ResponseStruct(java.lang.String result) {
        this.result = result;
    }
    
    public java.lang.String getResult() {
        return result;
    }
    
    public void setResult(java.lang.String result) {
        this.result = result;
    }
}
